server:
  port: ${port:8080}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${server.port}
    secure-port: 443
    hostname: ${HOSTNAME:localhost}

spring:
  application:
    name: ${APP_NAME:ms-library-operator}
  datasource:
    url: ${datasource_url:http://localhost}
    driver-class-name: org.postgresql.Driver
    username: ${datasource_username:local}
    password: ${datasource_password:none}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

url:
  searcher: ${url_searcher:http://ms-library-searcher}