server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: ms-library-operator

spring:
  application:
    name: ms-library-operator
  datasource:
    url: jdbc:postgresql://yamanote.proxy.rlwy.net:21996/railway
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: LRURZDKaoQMfHoPZwtvrUUPBNPUvdEdH
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

url:
  searcher: http://ms-library-searcher
