server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: ms-library-operator

spring:
  application:
    name: ms-library-operator
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:operator_db
  jpa:
    show-sql: true
    # defer-datasource-initialization: true

url:
  searcher: http://ms-library-searcher